import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget2/generated/GeneratedDumalaglarWidget2.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget2/generated/GeneratedGroup666Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget2/generated/GeneratedBackButtonWidget2.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 254, 254),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget2(),
              ),
              Positioned(
                left: 35.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 303.0,
                child: GeneratedGroup666Widget(),
              ),
              Positioned(
                left: 146.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 83.0527114868164,
                height: 13.263157844543457,
                child: GeneratedDumalaglarWidget2(),
              )
            ]),
      ),
    ));
  }
}
