import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedYangilogoWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedOvalCopy18Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/Generated12865removebgpreviewWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/Generated39381removebgpreviewWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedBitmapWidget9.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedBiheartpulseWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/Generated5790removebgpreviewWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/Generated33331838_medicinepillicontransparentbackgroundpillsclip.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedBitmapWidget11.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedBitmapWidget13.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedOvalWidget2.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedBitmapWidget12.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedBitmapWidget10.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedNotostethoscopeWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedLetsconsultwitdoWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedTwemojihospitalWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedOvalCopy19Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget4/generated/GeneratedLetsgetstartedWidget.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 254, 254),
                ),
              ),
              Positioned(
                left: 84.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 62.0,
                child: GeneratedGroupWidget2(),
              ),
              Positioned(
                left: 129.5,
                top: 579.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 23.0,
                child: GeneratedLetsconsultwitdoWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 43.0,
                child: GeneratedLetsgetstartedWidget(),
              ),
              Positioned(
                left: 265.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 166.0,
                child: Generated12865removebgpreviewWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 94.0,
                child: GeneratedBitmapWidget9(),
              ),
              Positioned(
                left: 82.0,
                top: 355.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: Generated5790removebgpreviewWidget(),
              ),
              Positioned(
                left: 418.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 138.0,
                child: Generated39381removebgpreviewWidget(),
              ),
              Positioned(
                left: 373.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 88.0,
                child: GeneratedBitmapWidget10(),
              ),
              Positioned(
                left: 157.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 34.0,
                child: GeneratedOvalCopy18Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedBitmapWidget11(),
              ),
              Positioned(
                left: 64.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedOvalCopy19Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBitmapWidget12(),
              ),
              Positioned(
                left: 178.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedOvalWidget2(),
              ),
              Positioned(
                left: 167.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 22.0,
                child: GeneratedBitmapWidget13(),
              ),
              Positioned(
                left: 131.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 125.80179595947266,
                child: GeneratedYangilogoWidget1(),
              ),
              Positioned(
                left: 315.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 68.0,
                child: GeneratedTwemojihospitalWidget(),
              ),
              Positioned(
                left: 307.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 45.0,
                child: GeneratedNotostethoscopeWidget(),
              ),
              Positioned(
                left: -10.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 41.72780990600586,
                child:
                    Generated33331838_medicinepillicontransparentbackgroundpillsclip(),
              ),
              Positioned(
                left: -2.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 57.0,
                child: GeneratedBiheartpulseWidget(),
              )
            ]),
      ),
    ));
  }
}
