import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedIllusWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedConnectwithyourmaWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedGroupCopyWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedRectangleWidget4.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/Generated62Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedWelcometoDocQWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedLineWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/Generated81391492186Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedRectangleWidget3.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedInsertyourphonenuWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedBitmapWidget6.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget3/generated/GeneratedCaret_downWidget.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 305.0,
                child: GeneratedRectangleWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBitmapWidget6(),
              ),
              Positioned(
                left: 30.0,
                top: 691.5,
                right: null,
                bottom: null,
                width: 315.0,
                height: 1.0,
                child: GeneratedLineWidget1(),
              ),
              Positioned(
                left: 108.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 28.0,
                child: Generated62Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 25.0,
                child: Generated81391492186Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 27.0,
                child: GeneratedWelcometoDocQWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 20.0,
                child: GeneratedInsertyourphonenuWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCaret_downWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedIllusWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 116.0,
                child: GeneratedConnectwithyourmaWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 723.3942260742188,
                right: null,
                bottom: null,
                width: 153.0,
                height: 45.605770111083984,
                child: GeneratedGroupCopyWidget1(),
              )
            ]),
      ),
    ));
  }
}
