import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedGroup1019Widget3.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/Generated2daysWidget.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedGroup1016Widget3.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedRectangle110Widget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedBackButtonWidget7.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedGroup1079Widget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedMichaelAmyWidget3.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/Generated7likesWidget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedVectorWidget87.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget3/generated/GeneratedGroup1012Widget3.dart';

/* Frame Diagnose
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiagnoseWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 153.00001525878906,
                top: 93.297119140625,
                right: null,
                bottom: null,
                width: 72.0,
                height: 20.0,
                child: GeneratedMichaelAmyWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 643.0,
                child: GeneratedGroup1016Widget3(),
              ),
              Positioned(
                left: 322.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 37.90129852294922,
                child: GeneratedGroup1012Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup1019Widget3(),
              ),
              Positioned(
                left: 14.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget7(),
              ),
              Positioned(
                left: 14.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 130.0,
                child: GeneratedRectangle110Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 44.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab(),
              ),
              Positioned(
                left: 299.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 7.0,
                child: Generated7likesWidget1(),
              ),
              Positioned(
                left: 291.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 11.0,
                child: Generated2daysWidget(),
              ),
              Positioned(
                left: 299.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 10.751646041870117,
                height: 9.29432487487793,
                child: GeneratedVectorWidget87(),
              ),
              Positioned(
                left: 21.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 15.0,
                child: GeneratedGroup1079Widget1(),
              )
            ]),
      ),
    ));
  }
}
