import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedGroup1031Widget2.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedBackButtonWidget14.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedCard5Widget13.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedGroup1006Widget1.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedGroup1045Widget5.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedTodaysmeetingsWidget2.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget4/generated/GeneratedButtonWidget10.dart';

/* Frame Schedule
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScheduleWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 54.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 37.0,
                child: GeneratedTodaysmeetingsWidget2(),
              ),
              Positioned(
                left: 64.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 19.0,
                child: GeneratedButtonWidget10(),
              ),
              Positioned(
                left: 18.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget14(),
              ),
              Positioned(
                left: 12.68115234375,
                top: 237.54345703125,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget13(),
              ),
              Positioned(
                left: 216.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 62.73828125,
                height: 14.379924774169922,
                child: GeneratedGroup1006Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedGroup1031Widget2(),
              ),
              Positioned(
                left: 13.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 347.8260803222656,
                height: 49.81884002685547,
                child: GeneratedGroup1045Widget5(),
              )
            ]),
      ),
    ));
  }
}
