import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/Generated5790removebgpreviewWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedOvalCopy19Widget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedYangilogoWidget2.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedOvalWidget6.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedGroup1028Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedLetsgetstartedWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedOvalWidget5.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedOvalWidget3.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedOvalWidget4.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget5/generated/GeneratedOvalCopy18Widget1.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedRegistrasiyaWidget4'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 254, 254, 254),
                  ),
                ),
                Positioned(
                  left: 82.0,
                  top: 355.0,
                  right: null,
                  bottom: null,
                  width: 128.0,
                  height: 128.0,
                  child: Generated5790removebgpreviewWidget1(),
                ),
                Positioned(
                  left: 157.0,
                  top: 112.0,
                  right: null,
                  bottom: null,
                  width: 34.0,
                  height: 34.0,
                  child: GeneratedOvalCopy18Widget1(),
                ),
                Positioned(
                  left: 64.0,
                  top: 233.0,
                  right: null,
                  bottom: null,
                  width: 46.0,
                  height: 46.0,
                  child: GeneratedOvalCopy19Widget1(),
                ),
                Positioned(
                  left: 178.0,
                  top: 376.0,
                  right: null,
                  bottom: null,
                  width: 46.0,
                  height: 46.0,
                  child: GeneratedOvalWidget3(),
                ),
                Positioned(
                  left: 370.0,
                  top: 429.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 54.0,
                  child: GeneratedOvalWidget4(),
                ),
                Positioned(
                  left: 333.0,
                  top: 134.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 54.0,
                  child: GeneratedOvalWidget5(),
                ),
                Positioned(
                  left: 122.0,
                  top: 472.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 54.0,
                  child: GeneratedOvalWidget6(),
                ),
                Positioned(
                  left: 63.0,
                  top: 279.0,
                  right: null,
                  bottom: null,
                  width: 250.0,
                  height: 308.3377380371094,
                  child: GeneratedYangilogoWidget2(),
                ),
                Positioned(
                  left: 129.0,
                  top: 674.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 43.0,
                  child: GeneratedLetsgetstartedWidget1(),
                ),
                Positioned(
                  left: 170.90213012695312,
                  top: 557.2571411132812,
                  right: null,
                  bottom: null,
                  width: 51.70847702026367,
                  height: 49.77109146118164,
                  child: GeneratedGroup1028Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
