import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget1/generated/GeneratedGroup1019Widget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget1/generated/GeneratedTODAYAT1045AMWidget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget1/generated/GeneratedGroup1016Widget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget1/generated/GeneratedBackButtonWidget5.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget1/generated/GeneratedMichaelAmyWidget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget1/generated/GeneratedGroup1012Widget1.dart';

/* Frame Diagnose
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiagnoseWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 149.99977111816406,
                top: 93.297119140625,
                right: null,
                bottom: null,
                width: 77.0,
                height: 24.0,
                child: GeneratedMichaelAmyWidget1(),
              ),
              Positioned(
                left: 173.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 19.0,
                child: GeneratedTODAYAT1045AMWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 643.0,
                child: GeneratedGroup1016Widget1(),
              ),
              Positioned(
                left: 322.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 37.90129852294922,
                child: GeneratedGroup1012Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup1019Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget5(),
              )
            ]),
      ),
    ));
  }
}
