import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget6/generated/GeneratedBackButtonWidget3.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget6/generated/GeneratedGroup935Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget6/generated/GeneratedGroup936Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget6/generated/GeneratedGroupWidget3.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget6/generated/GeneratedGroup667Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget6/generated/GeneratedDumalaglarWidget3.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 254, 254),
                ),
              ),
              Positioned(
                left: 83.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 62.0,
                child: GeneratedGroupWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget3(),
              ),
              Positioned(
                left: 36.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 262.0,
                child: GeneratedGroup667Widget(),
              ),
              Positioned(
                left: 146.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 83.0527114868164,
                height: 13.263157844543457,
                child: GeneratedDumalaglarWidget3(),
              ),
              Positioned(
                left: 308.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 11.078630447387695,
                child: GeneratedGroup935Widget(),
              ),
              Positioned(
                left: 308.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 11.079999923706055,
                child: GeneratedGroup936Widget(),
              )
            ]),
      ),
    ));
  }
}
