import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedImagepost11Widget2.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedInsertyourOTPCodeWidget1.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedDrDavronWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedPopularClinicsWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedDoctorbuttonWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedGroup978Widget4.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedGroup1049Widget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedDrShoxruxWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedGroup138Widget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedStarsWidget1.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedImagepost11Widget3.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedAntibioticWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedImagepost11Widget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedGroup970Widget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedVitaminsWidget1.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedGroup1025Widget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedDrNafisaWidget1.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedRecommendeddrugsWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedTopDoctorsWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedStarsWidget2.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedHomeIndicatorWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedOintmentWidget.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedStarsWidget3.dart';
import 'package:flutterapp/app_1app/generatedsearchwidget/generated/GeneratedHeaderWidget.dart';

/* Frame search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 82.0,
                top: -232.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 39.855072021484375,
                child: GeneratedHeaderWidget(),
              ),
              Positioned(
                left: 121.3768081665039,
                top: 799.81884765625,
                right: null,
                bottom: null,
                width: 132.15325927734375,
                height: 4.931091785430908,
                child: GeneratedHomeIndicatorWidget(),
              ),
              Positioned(
                left: 12.681159019470215,
                top: 407.60870361328125,
                right: null,
                bottom: null,
                width: 275.3623046875,
                height: 114.13043212890625,
                child: GeneratedGroup970Widget(),
              ),
              Positioned(
                left: 22.49267578125,
                top: 552.5361328125,
                right: null,
                bottom: null,
                width: 162.0,
                height: 24.0,
                child: GeneratedRecommendeddrugsWidget(),
              ),
              Positioned(
                left: 22.68115234375,
                top: 376.8115234375,
                right: null,
                bottom: null,
                width: 111.0,
                height: 24.0,
                child: GeneratedPopularClinicsWidget(),
              ),
              Positioned(
                left: 17.99993896484375,
                top: 665.7608642578125,
                right: null,
                bottom: null,
                width: 61.0,
                height: 24.0,
                child: GeneratedVitaminsWidget1(),
              ),
              Positioned(
                left: 199.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 24.0,
                child: GeneratedAntibioticWidget(),
              ),
              Positioned(
                left: 290.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 24.0,
                child: GeneratedOintmentWidget(),
              ),
              Positioned(
                left: 12.681159019470215,
                top: 590.5797119140625,
                right: null,
                bottom: null,
                width: 67.02898406982422,
                height: 67.02898406982422,
                child: GeneratedImagepost11Widget(),
              ),
              Positioned(
                left: 104.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 67.02898406982422,
                height: 90.0,
                child: GeneratedGroup1049Widget(),
              ),
              Positioned(
                left: 195.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 67.02898406982422,
                height: 67.02898406982422,
                child: GeneratedImagepost11Widget2(),
              ),
              Positioned(
                left: 286.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 67.02898406982422,
                height: 67.02898406982422,
                child: GeneratedImagepost11Widget3(),
              ),
              Positioned(
                left: 302.5362243652344,
                top: 407.60870361328125,
                right: null,
                bottom: null,
                width: 275.3623046875,
                height: 114.13043212890625,
                child: GeneratedGroup978Widget4(),
              ),
              Positioned(
                left: 17.0,
                top: 56.797119140625,
                right: null,
                bottom: null,
                width: 341.0,
                height: 36.0,
                child: GeneratedGroup1025Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 149.63999938964844,
                right: null,
                bottom: null,
                width: 393.0,
                height: 146.72000122070312,
                child: GeneratedDoctorbuttonWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 25.0,
                child: GeneratedTopDoctorsWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 23.0,
                child: GeneratedInsertyourOTPCodeWidget1(),
              ),
              Positioned(
                left: 34.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 16.538461685180664,
                child: GeneratedStarsWidget1(),
              ),
              Positioned(
                left: 169.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 16.538461685180664,
                child: GeneratedStarsWidget2(),
              ),
              Positioned(
                left: 315.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 16.538461685180664,
                child: GeneratedStarsWidget3(),
              ),
              Positioned(
                left: 47.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 20.0,
                child: GeneratedDrNafisaWidget1(),
              ),
              Positioned(
                left: 168.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 20.0,
                child: GeneratedDrShoxruxWidget(),
              ),
              Positioned(
                left: 325.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 20.0,
                child: GeneratedDrDavronWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 728.797119140625,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedGroup138Widget(),
              )
            ]),
      ),
    ));
  }
}
