import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedHeaderWidget2.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedCard5Widget6.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedUpcomingmeetingsWidget.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedBackButtonWidget10.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedCard5Widget5.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedCard5Widget7.dart';
import 'package:flutterapp/app_1app/generateddilshodwidget/generated/GeneratedGroup1045Widget1.dart';

/* Frame dilshod
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDilshodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 39.855072021484375,
                child: GeneratedHeaderWidget2(),
              ),
              Positioned(
                left: 64.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 19.0,
                child: GeneratedButtonWidget2(),
              ),
              Positioned(
                left: 11.775390625,
                top: 237.6884307861328,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget5(),
              ),
              Positioned(
                left: 18.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget10(),
              ),
              Positioned(
                left: 12.68115234375,
                top: 395.5434875488281,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget6(),
              ),
              Positioned(
                left: 11.775390625,
                top: 556.3985595703125,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget7(),
              ),
              Positioned(
                left: 13.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 347.8260803222656,
                height: 49.81884002685547,
                child: GeneratedGroup1045Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 38.0,
                child: GeneratedUpcomingmeetingsWidget(),
              )
            ]),
      ),
    ));
  }
}
