import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedWhoareyouWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedOvalCopy2Widget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedBackButtonWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedHealthWorkerLightSkinToneWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedDumalaglarWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedDowncastFaceWithSweatWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedPsycologyWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedGroupWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedOvalCopy5Widget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedDentistWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedMouthCopy3Widget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedYangilogoWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedOvalWidget1.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget1/generated/GeneratedGroup659Widget1.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 254, 254),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 308.3377380371094,
                child: GeneratedYangilogoWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 62.0,
                child: GeneratedGroupWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedWhoareyouWidget(),
              ),
              Positioned(
                left: 146.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 83.0527114868164,
                height: 13.263157844543457,
                child: GeneratedDumalaglarWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget1(),
              ),
              Positioned(
                left: 152.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 81.98194885253906,
                height: 81.98194885253906,
                child: GeneratedOvalWidget1(),
              ),
              Positioned(
                left: 249.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 81.98194885253906,
                height: 81.98194885253906,
                child: GeneratedOvalCopy2Widget1(),
              ),
              Positioned(
                left: 49.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 81.98194885253906,
                height: 81.98194885253906,
                child: GeneratedOvalCopy5Widget1(),
              ),
              Positioned(
                left: 169.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 23.0,
                child: GeneratedDentistWidget1(),
              ),
              Positioned(
                left: 67.0,
                top: 460.11083984375,
                right: null,
                bottom: null,
                width: 50.0,
                height: 23.0,
                child: GeneratedPsycologyWidget1(),
              ),
              Positioned(
                left: 274.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 23.0,
                child: GeneratedMouthCopy3Widget1(),
              ),
              Positioned(
                left: 306.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 23.168813705444336,
                height: 23.168813705444336,
                child: GeneratedGroup659Widget1(),
              ),
              Positioned(
                left: 86.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 52.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 175.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedDowncastFaceWithSweatWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 34.0,
                child: GeneratedHealthWorkerLightSkinToneWidget(),
              )
            ]),
      ),
    ));
  }
}
