import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedRectangle79Widget5.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedGroup1075Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedStarsWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedGroup1003Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedAppointmentWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedFargonashaharANavoiy102uyWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedDrNafisaWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedAboutWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedGroup1064Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab2.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedRectangle73Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedKeyboard_arrow_leftWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedTraumatologistWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedGroup1056Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget/generated/GeneratedRectangle82Widget.dart';

/* Frame Doctor info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoctorinfoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.59423828125,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -0.0000820159912109375,
                right: null,
                bottom: null,
                width: 375.0,
                height: 281.7029113769531,
                child: GeneratedRectangle82Widget(),
              ),
              Positioned(
                left: 13.251571655273438,
                top: 349.43243408203125,
                right: null,
                bottom: null,
                width: 352.54345703125,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab2(),
              ),
              Positioned(
                left: 13.8226318359375,
                top: 320.4472961425781,
                right: null,
                bottom: null,
                width: 52.0,
                height: 28.0,
                child: GeneratedAboutWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 324.2753601074219,
                height: 131.340576171875,
                child: GeneratedRectangle73Widget(),
              ),
              Positioned(
                left: 145.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 90.38461303710938,
                height: 20.0,
                child: GeneratedTraumatologistWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 11.0,
                child: GeneratedFargonashaharANavoiy102uyWidget(),
              ),
              Positioned(
                left: 137.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 28.0,
                child: GeneratedDrNafisaWidget(),
              ),
              Positioned(
                left: 46.617279052734375,
                top: 716.8253173828125,
                right: null,
                bottom: null,
                width: 273.4999694824219,
                height: 48.00724792480469,
                child: GeneratedRectangle79Widget5(),
              ),
              Positioned(
                left: 138.5302734375,
                top: 730.4122314453125,
                right: null,
                bottom: null,
                width: 95.0,
                height: 25.0,
                child: GeneratedAppointmentWidget(),
              ),
              Positioned(
                left: 8.15234375,
                top: 14.4931640625,
                right: null,
                bottom: null,
                width: 31.702898025512695,
                height: 31.702898025512695,
                child: GeneratedKeyboard_arrow_leftWidget(),
              ),
              Positioned(
                left: 123.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 128.504638671875,
                height: 19.0,
                child: GeneratedGroup1056Widget(),
              ),
              Positioned(
                left: 12.17193603515625,
                top: 428.3110656738281,
                right: null,
                bottom: null,
                width: 325.3297119140625,
                height: 106.26126861572266,
                child: GeneratedGroup1003Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 314.6337585449219,
                height: 77.80154418945312,
                child: GeneratedGroup1064Widget(),
              ),
              Positioned(
                left: 107.0,
                top: 268.41748046875,
                right: null,
                bottom: null,
                width: 160.8272705078125,
                height: 25.362319946289062,
                child: GeneratedGroup1075Widget(),
              ),
              Positioned(
                left: 234.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 137.99981689453125,
                height: 26.538461685180664,
                child: GeneratedStarsWidget(),
              )
            ]),
      ),
    ));
  }
}
