import 'package:flutter/material.dart';

/* Text 🏥
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''🏥''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.9761904545821691,
        fontSize: 29.423076629638672,
        fontFamily: 'Mulish',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
