import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedCard5Widget3.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedGroup1045Widget.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedTodaysmeetingsWidget.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedGroup1006Widget.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedCard5Widget2.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedGroup1031Widget.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedCard5Widget4.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget/generated/GeneratedBackButtonWidget9.dart';

/* Frame Schedule
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScheduleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 54.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 37.0,
                child: GeneratedTodaysmeetingsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 39.855072021484375,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 64.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 19.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 11.775390625,
                top: 237.6884307861328,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget9(),
              ),
              Positioned(
                left: 12.68115234375,
                top: 395.5434875488281,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget3(),
              ),
              Positioned(
                left: 11.775390625,
                top: 556.3985595703125,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget4(),
              ),
              Positioned(
                left: 216.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 62.73828125,
                height: 14.379924774169922,
                child: GeneratedGroup1006Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedGroup1031Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 347.8260803222656,
                height: 49.81884002685547,
                child: GeneratedGroup1045Widget(),
              )
            ]),
      ),
    ));
  }
}
