import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedframe999widget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/app_1app/generatedframe999widget/generated/GeneratedGroup1032Widget1.dart';
import 'package:flutterapp/app_1app/generatedframe999widget/generated/GeneratedGroup1029Widget1.dart';
import 'package:flutterapp/app_1app/generatedframe999widget/generated/GeneratedMedsageWidget4.dart';
import 'package:flutterapp/app_1app/generatedframe999widget/generated/GeneratedDrNodirbekWidget1.dart';
import 'package:flutterapp/app_1app/generatedframe999widget/generated/GeneratedIllusWidget2.dart';

/* Frame Frame 999
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame999Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 247, 247),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 22.0,
                child: GeneratedDrNodirbekWidget1(),
              ),
              Positioned(
                left: 89.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 184.9999237060547,
                height: 194.62229919433594,
                child: GeneratedGroup1029Widget1(),
              ),
              Positioned(
                left: 123.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 46.0,
                child: GeneratedMedsageWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 526.0,
                child: GeneratedGroup1032Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIllusWidget2(),
              )
            ]),
      ),
    ));
  }
}
