import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedGroup1045Widget6.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedBackButtonWidget15.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedTodaysmeetingsWidget3.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedGroup1031Widget3.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedHeaderWidget6.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget5/generated/GeneratedCard5Widget14.dart';

/* Frame Schedule
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScheduleWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 54.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 37.0,
                child: GeneratedTodaysmeetingsWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 39.855072021484375,
                child: GeneratedHeaderWidget6(),
              ),
              Positioned(
                left: 64.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 19.0,
                child: GeneratedButtonWidget12(),
              ),
              Positioned(
                left: 11.775390625,
                top: 237.6884307861328,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget14(),
              ),
              Positioned(
                left: 18.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget15(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedGroup1031Widget3(),
              ),
              Positioned(
                left: 13.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 347.8260803222656,
                height: 49.81884002685547,
                child: GeneratedGroup1045Widget6(),
              )
            ]),
      ),
    ));
  }
}
