import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedCard5Widget8.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedCard5Widget9.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedBackButtonWidget11.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedGroup1045Widget2.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedHeaderWidget3.dart';
import 'package:flutterapp/app_1app/generatedschedulewidget1/generated/GeneratedUpcomingmeetingsWidget1.dart';

/* Frame Schedule
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScheduleWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 39.855072021484375,
                child: GeneratedHeaderWidget3(),
              ),
              Positioned(
                left: 64.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 19.0,
                child: GeneratedButtonWidget4(),
              ),
              Positioned(
                left: 11.775390625,
                top: 237.6884307861328,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget8(),
              ),
              Positioned(
                left: 18.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget11(),
              ),
              Positioned(
                left: 11.775390625,
                top: 395.3984375,
                right: null,
                bottom: null,
                width: 348.73187255859375,
                height: 147.64492797851562,
                child: GeneratedCard5Widget9(),
              ),
              Positioned(
                left: 13.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 347.8260803222656,
                height: 49.81884002685547,
                child: GeneratedGroup1045Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 38.0,
                child: GeneratedUpcomingmeetingsWidget1(),
              )
            ]),
      ),
    ));
  }
}
