import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedGroup1078Widget.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedGroup1016Widget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedGroup1019Widget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedGroup1012Widget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedMichaelAmyWidget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedBackButtonWidget6.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget2/generated/GeneratedGroup1079Widget.dart';

/* Frame Diagnose
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiagnoseWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 116.00001525878906,
                top: 93.297119140625,
                right: null,
                bottom: null,
                width: 145.0,
                height: 20.0,
                child: GeneratedMichaelAmyWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 643.0,
                child: GeneratedGroup1016Widget2(),
              ),
              Positioned(
                left: 322.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 37.90129852294922,
                child: GeneratedGroup1012Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup1019Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget6(),
              ),
              Positioned(
                left: 14.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 201.0,
                child: GeneratedGroup1078Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 15.0,
                child: GeneratedGroup1079Widget(),
              )
            ]),
      ),
    ));
  }
}
