import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedAppointmentWidget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedMRTWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedKeyboard_arrow_leftWidget2.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle108Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab5.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle82Widget2.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedGroup1077Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle105Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedMSKTWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedGroup1056Widget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle106Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedXRayWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle73Widget2.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedNANOMedicalClinicWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedGroup1064Widget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle79Widget6.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle107Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedRectangle109Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedGroup1003Widget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedAboutWidget2.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget2/generated/GeneratedLaboratoryWidget.dart';

/* Frame Doctor info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoctorinfoWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.59423828125,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -0.0000820159912109375,
                right: null,
                bottom: null,
                width: 375.0,
                height: 281.7029113769531,
                child: GeneratedRectangle82Widget2(),
              ),
              Positioned(
                left: 13.25146484375,
                top: 344.432373046875,
                right: null,
                bottom: null,
                width: 352.54345703125,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab5(),
              ),
              Positioned(
                left: 13.82275390625,
                top: 315.447265625,
                right: null,
                bottom: null,
                width: 52.0,
                height: 28.0,
                child: GeneratedAboutWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 108.0,
                child: GeneratedRectangle73Widget2(),
              ),
              Positioned(
                left: 102.0,
                top: 268.41748046875,
                right: null,
                bottom: null,
                width: 170.441650390625,
                height: 25.362319946289062,
                child: GeneratedGroup1077Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 24.0,
                child: GeneratedNANOMedicalClinicWidget(),
              ),
              Positioned(
                left: 46.617279052734375,
                top: 716.8253173828125,
                right: null,
                bottom: null,
                width: 273.4999694824219,
                height: 48.00724792480469,
                child: GeneratedRectangle79Widget6(),
              ),
              Positioned(
                left: 138.5302734375,
                top: 730.4122314453125,
                right: null,
                bottom: null,
                width: 95.0,
                height: 25.0,
                child: GeneratedAppointmentWidget1(),
              ),
              Positioned(
                left: 8.15234375,
                top: 14.4931640625,
                right: null,
                bottom: null,
                width: 31.702898025512695,
                height: 31.702898025512695,
                child: GeneratedKeyboard_arrow_leftWidget2(),
              ),
              Positioned(
                left: 123.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 24.0,
                child: GeneratedGroup1056Widget1(),
              ),
              Positioned(
                left: 12.171875,
                top: 482.31103515625,
                right: null,
                bottom: null,
                width: 325.3297119140625,
                height: 106.26126861572266,
                child: GeneratedGroup1003Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 314.6337585449219,
                height: 77.80154418945312,
                child: GeneratedGroup1064Widget1(),
              ),
              Positioned(
                left: 12.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 66.0,
                child: GeneratedRectangle105Widget(),
              ),
              Positioned(
                left: 98.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 66.0,
                child: GeneratedRectangle106Widget(),
              ),
              Positioned(
                left: 184.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 66.0,
                child: GeneratedRectangle107Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 66.0,
                child: GeneratedRectangle108Widget(),
              ),
              Positioned(
                left: 356.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 66.0,
                child: GeneratedRectangle109Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 22.0,
                child: GeneratedMRTWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 22.0,
                child: GeneratedMSKTWidget(),
              ),
              Positioned(
                left: 189.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 22.0,
                child: GeneratedXRayWidget(),
              ),
              Positioned(
                left: 273.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 39.0,
                child: GeneratedLaboratoryWidget(),
              )
            ]),
      ),
    ));
  }
}
