import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedKeyboard_arrow_leftWidget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedContainsWidget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedGroup1073Widget.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedAboutWidget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedRectangle82Widget1.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab3.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab4.dart';
import 'package:flutterapp/app_1app/generateddoctorinfowidget1/generated/GeneratedGroup1072Widget.dart';

/* Frame Doctor info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoctorinfoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.59423828125,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -0.0000820159912109375,
                right: null,
                bottom: null,
                width: 375.0,
                height: 281.7029113769531,
                child: GeneratedRectangle82Widget1(),
              ),
              Positioned(
                left: 13.25146484375,
                top: 405.4326171875,
                right: null,
                bottom: null,
                width: 352.54345703125,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab3(),
              ),
              Positioned(
                left: 14.0,
                top: 509.9853515625,
                right: null,
                bottom: null,
                width: 352.54345703125,
                height: 59.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab4(),
              ),
              Positioned(
                left: 13.82275390625,
                top: 376.447265625,
                right: null,
                bottom: null,
                width: 52.0,
                height: 28.0,
                child: GeneratedAboutWidget1(),
              ),
              Positioned(
                left: 14.5712890625,
                top: 481.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 28.0,
                child: GeneratedContainsWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 88.0,
                child: GeneratedGroup1072Widget(),
              ),
              Positioned(
                left: 8.15234375,
                top: 14.4931640625,
                right: null,
                bottom: null,
                width: 31.702898025512695,
                height: 31.702898025512695,
                child: GeneratedKeyboard_arrow_leftWidget1(),
              ),
              Positioned(
                left: 11.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedGroup1073Widget(),
              )
            ]),
      ),
    ));
  }
}
