import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedMedsageWidget3.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedDrNodirbekWidget.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedGroup1029Widget.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedStatusIconsWidget.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedGroup1032Widget.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedIllusWidget1.dart';
import 'package:flutterapp/app_1app/generatedframe996widget/generated/GeneratedHomeWidget.dart';

/* Frame Frame 996
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame996Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 22.0,
                child: GeneratedDrNodirbekWidget(),
              ),
              Positioned(
                left: 89.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 184.9999237060547,
                height: 194.62229919433594,
                child: GeneratedGroup1029Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 46.0,
                child: GeneratedMedsageWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 526.0,
                child: GeneratedGroup1032Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 14.0,
                child: GeneratedStatusIconsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIllusWidget1(),
              )
            ]),
      ),
    ));
  }
}
