import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedGroup1079Widget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/Generated7likesWidget2.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedRectangle110Widget3.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedGroup1019Widget4.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedMichaelAmyWidget4.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedGroup1012Widget4.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedVectorWidget96.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/Generated2daysWidget1.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedGroup1016Widget4.dart';
import 'package:flutterapp/app_1app/generateddiagnosewidget4/generated/GeneratedBackButtonWidget8.dart';

/* Frame Diagnose
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDiagnoseWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 811.5941772460938,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 247, 250, 254),
                ),
              ),
              Positioned(
                left: 161.00001525878906,
                top: 93.297119140625,
                right: null,
                bottom: null,
                width: 58.0,
                height: 23.0,
                child: GeneratedMichaelAmyWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 643.0,
                child: GeneratedGroup1016Widget4(),
              ),
              Positioned(
                left: 322.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 37.90129852294922,
                child: GeneratedGroup1012Widget4(),
              ),
              Positioned(
                left: 25.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedGroup1019Widget4(),
              ),
              Positioned(
                left: 14.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget8(),
              ),
              Positioned(
                left: 14.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 130.0,
                child: GeneratedRectangle110Widget3(),
              ),
              Positioned(
                left: 21.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 44.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitProinhab1(),
              ),
              Positioned(
                left: 299.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 7.0,
                child: Generated7likesWidget2(),
              ),
              Positioned(
                left: 291.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 11.0,
                child: Generated2daysWidget1(),
              ),
              Positioned(
                left: 299.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 10.751646041870117,
                height: 9.29432487487793,
                child: GeneratedVectorWidget96(),
              ),
              Positioned(
                left: 21.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 15.0,
                child: GeneratedGroup1079Widget2(),
              )
            ]),
      ),
    ));
  }
}
