import 'package:flutter/material.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget/generated/GeneratedGroup668Widget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget/generated/GeneratedBackButtonWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget/generated/GeneratedDumalaglarWidget.dart';
import 'package:flutterapp/app_1app/generatedregistrasiyawidget/generated/GeneratedGroupWidget.dart';

/* Frame registrasiya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrasiyaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 254, 254, 254),
                ),
              ),
              Positioned(
                left: 83.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 62.0,
                child: GeneratedGroupWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 291.59033203125,
                height: 366.0,
                child: GeneratedGroup668Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBackButtonWidget(),
              ),
              Positioned(
                left: 146.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 83.0527114868164,
                height: 13.263157844543457,
                child: GeneratedDumalaglarWidget(),
              )
            ]),
      ),
    ));
  }
}
